name: Deploy Landing Page to Cloudflare
run-name: Build on ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches: [main, dev]

jobs:
  landing-page:
    name: Landing Page Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
        with:
          path: source
      - name: Cloudflare Deploy
        id: cloudflare-deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy source/landing --project-name=domain-main-page --branch=${{ github.ref_name }}
